"""Revisión de compatibilidad

Revision ID: 94aa1c6a04b5
Revises: a86018cdf768
Create Date: 2024-12-28 02:03:34.810509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94aa1c6a04b5'
down_revision: Union[str, None] = 'a86018cdf768'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
